baseURL = "https://www.skyzh.dev/"
copyright = "© Alex Chi"
languageCode = "en-us"
theme = "hugo-ink"
title = "Alex Chi"
# Code Highlight
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsstyle = "vs"
paginate = 10 # articles per page

googleAnalytics = "G-812BQ96S8Q"

[params]
avatar = "/skyzh.jpg"
mode = "light"
featherIconsCDN = true
subtitle = "Code for fun, Make things happen"
excludedTypes = ["page", "pages"]
images = ['skyzh.jpg']

[[params.social]]
icon = "github"
name = "GitHub"
url = "https://github.com/skyzh"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
